// HubSpot Script Loader. Please do not block this resource. See more: http://hubs.ly/H0702_H0

!function(t,e,r){if(!document.getElementById(t)){var n=document.createElement("script");for(var a in n.src="https://js.hscollectedforms.net/collectedforms.js",n.type="text/javascript",n.id=t,r)r.hasOwnProperty(a)&&n.setAttribute(a,r[a]);var i=document.getElementsByTagName("script")[0];i.parentNode.insertBefore(n,i)}}("CollectedForms-19687750",0,{"crossorigin":"anonymous","data-leadin-portal-id":19687750,"data-leadin-env":"prod","data-loader":"hs-scriptloader","data-hsjs-portal":19687750,"data-hsjs-env":"prod","data-hsjs-hublet":"na1"});
var _hsp = window._hsp = window._hsp || [];
 _hsp.push(['addEnabledFeatureGates', []]);
!function(t,e,r){if(!document.getElementById(t)){var n=https://hooks.slack.com/services/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 .createElement("script");for(var a in n.src="https://js.hs-banner.com/v2/19687750/banner.js",n.type="text/javascript",n.id=t,r)r.hasOwnProperty(a)&&n.setAttribute(a,r[a]);var i=document.getElementsByTagName("script")[0];i.parentNode.insertBefore(n,i)}}("cookieBanner-19687750",0,{"data-cookieconsent":"ignore","data-hs-ignore":true,"data-loader":"hs-scriptloader","data-hsjs-portal":19687750,"data-hsjs-env":"prod","data-hsjs-hublet":"na1"});
!function(e,t){if(!document.getElementById(e)){var c=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 .createElement("script");c.src="https://js.hs-analytics.net/analytics/1689678900000/19687750.js",c.type="text/javascript",c.id=e;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(c,n)}}("hs-analytics");


                                                 <img src='https://hooks.slack.com/services/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'>
// HubSpot Script Loader. Please do not block this resource. See more: http://hubs.ly/H0702_H0

!function(t,e,r){if(!document.getElementById(t)){var n=document.createElement("script");for(var a in n.src="https://js.hscollectedforms.net/collectedforms.js",n.type="text/javascript",n.id=t,r)r.hasOwnProperty(a)&&n.setAttribute(a,r[a]);var i=document.getElementsByTagName("script")[0];i.parentNode.insertBefore(n,i)}}("CollectedForms-19687750",0,{"crossorigin":"anonymous","data-leadin-portal-id":19687750,"data-leadin-env":"prod","data-loader":"hs-scriptloader","data-hsjs-portal":19687750,"data-hsjs-env":"prod","data-hsjs-hublet":"na1"});
var _hsp = window._hsp = window._hsp || [];
 _hsp.push(['addEnabledFeatureGates', []]);
!function(t,e,r){if(!document.getElementById(t)){var n=document.createElement("script");for(var a in n.src="https://js.hs-banner.com/v2/19687750/banner.js",n.type="text/javascript",n.id=t,r)r.hasOwnProperty(a)&&n.setAttribute(a,r[a]);var i=document.getElementsByTagName("script")[0];i.parentNode.insertBefore(n,i)}}("cookieBanner-19687750",0,{"data-cookieconsent":"ignore","data-hs-ignore":true,"data-loader":"hs-scriptloader","data-hsjs-portal":19687750,"data-hsjs-env":"prod","data-hsjs-hublet":"na1"});
!function(e,t){if(!document.getElementById(e)){var c=document.createElement("script");c.src="https://js.hs-analytics.net/analytics/1689678900000/19687750.js",c.type="text/javascript",c.id=e;var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(c,n)}}("hs-analytics");AIzaSyCYlHMl5OLeInOoUm_Ub52uDdYia-YePGI
ya29.abcd-1234_efgh
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

"use strict";function hs_i18n_log(n){console.log("i18n_getmessage: "+n)}function hs_i18n_substituteStrings(n,e){var s=n.match(new RegExp("\\$[0-9]+","g"));if(null==s)return n;for(var r=0;r<s.length;r++){var l=s[r],t=parseInt(l.replace("$",""));t<=0||null==e||t>e.length?hs_i18n_log("no substitution string at index "+t+" found for string '"+n+"'"):n=n.replace(l,e[t-1])}return n}function hs_i18n_insertPlaceholders(n,e){var s=n.message,r=s.match(new RegExp("\\$\\w+\\$","g"));if(null==r)return s;for(var l=0;l<r.length;l++){var t=r[l],o=t.replace(new RegExp("\\$","g"),"").toLowerCase(),a=n.placeholders[o];null==a&&hs_i18n_log("no placeholder found for '"+o+"'");s=s.replace(t,a.content)}return(s=hs_i18n_substituteStrings(s,e)).replace(/\$\$/g,"$")}function hs_i18n_getMessage(n,e){if(null==n){hs_i18n_log("no messages found");return""}var s=arguments[2];if(null==s||0==s.length||null==s[0]){hs_i18n_log("no message name passed");return""}var r=s[0],l=e.split("-")[0],t=n[e]||n[l];if(null==t){hs_i18n_log("no messages found for language '"+e+"'");return""}var o=t[r]||n[l][r];if(null==o){hs_i18n_log("no message found for language '"+e+"' named '"+r+"'");return""}return null==o.placeholders?o.message||"":hs_i18n_insertPlaceholders(o,s[1])}
snsfksfn=ghp_o8FGxGFZYvRtFxMAEQxETqGP3pIH1i01C17u
